# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy

class PierceCountyDescriptionItem(scrapy.Item):
    owner_name = scrapy.Field()
    owner_last_name = scrapy.Field()
    owner_first_name = scrapy.Field()
    parcel = scrapy.Field()
    site_address = scrapy.Field()
    mailing_address = scrapy.Field()
    mail_city = scrapy.Field()
    mail_state = scrapy.Field()
    mail_zip = scrapy.Field()
    tax_year_1 = scrapy.Field()
    tax_year_2 = scrapy.Field()
    tax_year_3 = scrapy.Field()
    tax_year_1_assessed = scrapy.Field()
    tax_year_2_assessed = scrapy.Field()
    tax_year_3_assessed = scrapy.Field()
    current_balance_due = scrapy.Field()
    square_footage = scrapy.Field()
    acres = scrapy.Field()
    electric = scrapy.Field()
    sewer = scrapy.Field()
    water = scrapy.Field()
    property_type = scrapy.Field()
    occupancy = scrapy.Field()
    building_square_footage = scrapy.Field()
    lot_square_footage = scrapy.Field()
    lot_acres = scrapy.Field()
    attached_garage_footage = scrapy.Field()
    year_built = scrapy.Field()
    adj_year_built = scrapy.Field()
    stories = scrapy.Field()
    bedrooms = scrapy.Field()
    baths = scrapy.Field()
    siding_type = scrapy.Field()
    units = scrapy.Field()
    sale_price = scrapy.Field()
    sale_date = scrapy.Field()


class DuvalCountyDescriptionItem(scrapy.Item):
    parcel = scrapy.Field()
    owner_name = scrapy.Field()
    occupancy = scrapy.Field()
    site_address = scrapy.Field()
    mailing_address = scrapy.Field()
    property_type = scrapy.Field()
    building_square_footage = scrapy.Field()
    attached_garage_footage = scrapy.Field()
    year_built = scrapy.Field()
    adj_year_built = scrapy.Field()
    stories = scrapy.Field()
    baths = scrapy.Field()
    bedrooms = scrapy.Field()
    siding_type = scrapy.Field()
    units = scrapy.Field()
    sale1_price = scrapy.Field()
    sale1_date = scrapy.Field()
    sale2_price = scrapy.Field()
    sale2_date = scrapy.Field()
    tax_year_1 = scrapy.Field()
    tax_year_2 = scrapy.Field()
    tax_year_3 = scrapy.Field()
    tax_year_1_assessed = scrapy.Field()
    tax_year_2_assessed = scrapy.Field()
    tax_year_3_assessed = scrapy.Field()
    lot_square_footage = scrapy.Field()
    lot_acres = scrapy.Field()
    electric = scrapy.Field()
    sewer = scrapy.Field()
    units = scrapy.Field()
    water = scrapy.Field()


class CookCountyDescriptionItem(scrapy.Item):
    parcel = scrapy.Field()
    owner_name = scrapy.Field()
    site_address_street = scrapy.Field()
    site_address_city = scrapy.Field()
    site_address_zip = scrapy.Field()
    site_address_township = scrapy.Field()
    mailing_address_city_zip_state = scrapy.Field()
    mailing_address_street = scrapy.Field()
    age = scrapy.Field()
    lot_square_footage = scrapy.Field()
    building_square_footage = scrapy.Field()
    current_year_assessed_value = scrapy.Field()
    prior_year_assessed_value = scrapy.Field()
    property_use = scrapy.Field()
    residence_type = scrapy.Field()
    units = scrapy.Field()
    construction_type = scrapy.Field()
    full_bathrooms = scrapy.Field()
    half_bathrooms = scrapy.Field()
    basement = scrapy.Field()
    central_air = scrapy.Field()
    garage_type = scrapy.Field()
    home_owner_exemption = scrapy.Field()
    senior_citizen_exemption = scrapy.Field()





